# FROM ubuntu:20.10
# ARG DEBIAN_FRONTEND=noninteractive
# RUN apt update; apt upgrade

# RUN apt install -y wget sudo
# RUN apt install -y openjdk-11-jre


# RUN mkdir /app
# WORKDIR /app

# RUN wget https://github.com/thingsboard/thingsboard/releases/download/v3.3.2/thingsboard-3.3.2.deb
# RUN sudo dpkg -i thingsboard-3.3.2.deb

# RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
# USER docker



FROM openjdk:11-buster

RUN apt-get update
RUN apt install -y openjdk-11-jre
RUN apt-get install -y curl gnupg2 wget
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main' | tee --append /etc/apt/sources.list.d/pgdg.list > /dev/null
RUN curl -L https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
ENV PG_MAJOR 12
RUN apt-get update
RUN apt-get install -y postgresql-12
RUN update-rc.d postgresql disable

COPY logback.xml thingsboard.conf start-db.sh stop-db.sh start-tb.sh upgrade-tb.sh install-tb.sh /tmp/
RUN cd /tmp
RUN wget https://github.com/thingsboard/thingsboard/releases/download/v3.3.2/thingsboard-3.3.2.deb

RUN chmod a+x /tmp/*.sh \
    && mv /tmp/start-tb.sh /usr/bin \
    && mv /tmp/upgrade-tb.sh /usr/bin \
    && mv /tmp/install-tb.sh /usr/bin \
    && mv /tmp/start-db.sh /usr/bin \
    && mv /tmp/stop-db.sh /usr/bin

RUN dpkg -i thingsboard-3.3.2.deb
# RUN rm thingsboard-3.3.2.deb

RUN systemctl --no-reload disable --now thingsboard.service > /dev/null 2>&1 || :

RUN mv /tmp/logback.xml /usr/share/thingsboard/conf \
    && mv /tmp/thingsboard.conf /usr/share/thingsboard/conf

ENV DATA_FOLDER=/data

ENV HTTP_BIND_PORT=9090
ENV DATABASE_TS_TYPE=sql

ENV PGDATA=/data/db
ENV PATH=$PATH:/usr/lib/postgresql/$PG_MAJOR/bin

ENV SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
ENV SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/thingsboard
ENV SPRING_DATASOURCE_USERNAME=postgres
ENV SPRING_DATASOURCE_PASSWORD=postgres


ENV PGLOG=/var/log/postgres
RUN mkdir -p $PGLOG
RUN chown -R postgres:postgres $PGLOG

RUN chown -R postgres:postgres /var/run/postgresql

RUN mkdir -p /data
RUN chown -R postgres:postgres /data

RUN chown -R postgres:postgres /var/log/thingsboard
RUN chmod 555 /usr/share/thingsboard/bin/thingsboard.jar

USER postgres

EXPOSE 9090
EXPOSE 1883
EXPOSE 5683/udp
EXPOSE 5685/udp

# VOLUME ["/data"]